name: Main Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci-fast:
    name: CI Fast
    uses: ./.github/workflows/ci-fast.yml
    secrets: inherit

  cd:
    name: CD
    needs: [ci-fast]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/cd.yml
    secrets: inherit
    permissions:
      contents: write
